#!/usr/bin/env bash

/usr/local/bin/sbt package

cp target/scala-2.11/singleaxis_2.11-0.3-SNAPSHOT.jar /Users/smichaels/Desktop/singleaxis/lib/org.tmt.aps.ics.singleaxis_2.11-0.3-SNAPSHOT.jar

cp scripts/singleaxis /Users/smichaels/Desktop/singleaxis/bin/singleaxis

cp scripts/singleaxisclient /Users/smichaels/Desktop/singleaxis/bin/singleaxisclient

cp scripts/singleaxisclient2 /Users/smichaels/Desktop/singleaxis/bin/singleaxisclient2
